### PR TITLE
Further Refactoring

### PR DESCRIPTION
**Pull request by QuestofIranon**
I did some minor refactoring on top of #14 

Includes the API improvements, fixes, and most of the performance boosts from #14 but uses newer dependencies based on recent advances in the Rust ecosystem.

- replaces `FxHashMap` with `hashbrown` for ~2x the performance boost (~8x performance boost on top of the original hashmap). `hashbrown` is also going to be merged into the rust std so it will allow for the dependency to be dropped in the future.

- removes `ring` as a dependency in favor of smaller specialized crypto libs that have came out of rust crypto recently. No longer depends on ssl implementations.

### CODE REVIEW

**Comment by steveatinfincia** [comment]
Hey this looks good, I'll take a closer look tomorrow and get it merged :)

**Comment by QuestofIranon** [comment]
I should mention that one of my intentions with the changes in this PR was for better support across platforms, acknowledging the performance cost.

**Comment by maciejhirsz** [comment]
That makes sense. The performance degradation isn't bad at all (and it's still way faster than what it used to be prior to #14) so that seems like a reasonable trade-off.

**Comment by QuestofIranon** [comment]
I made another change that makes the non-English languages compile time features, though I left them all enabled by default. I thought this would be nice as an optional enhancement because it reduces the size of the compiled library by almost half.

With default features disabled (only English) the size of the `.rlib` is `664 KB` compared to `1390 KB` with all languages.

The main downside is that currently English is always included even if you specify other languages. I needed a default language due to the current implementation and it is the standard language defined in bip. I might look into ways around this but thought it might be worth discussing first. @maciejhirsz @steveatinfincia

**Comment by steveatinfincia** [comment]
This is released on Cargo now as the `v0.6.0-beta.1` tag

**Pull request merged**
