### PR TITLE
word phrases typed by people might have extra whitespace, tolerate this

### LINKED ISSUE #23: Mnemonic::from_phrase() intolerant of spaces
as the title suggests, a user typing words or copy-pasting may include additional whitespace in a seed phrase

it might be nice to tolerate these

### PR DESCRIPTION
**Pull request by rob-solana**
fixes #23

### CODE REVIEW

**Comment by rob-solana** [comment]
CC @maciejhirsz

**Comment by maciejhirsz** [comment]
@rob-solana this is tricky, because the phrase itself, not the entropy, is what is being hashed, so if you validate a phrase with extra spaces, you will produce an invalid seed for that phrase, which is way worse than rejecting the phrase due to extra spaces. This could be doubly problematic if you handled other whitespace characters (tab, feed, or new line).

IMO a better way to handle this would be to return a specialized error if the phrase contains extra spaces. The `Mnemonic::from_phrase` method could then handle that error and try to sanitize the string before retrying.

**Comment by rob-solana** [comment]
> @rob-solana this is tricky, because the phrase itself, not the entropy, is what is being hashed, so if you validate a phrase with extra spaces, you will produce an invalid seed for that phrase, which is way worse than rejecting the phrase due to extra spaces. This could be doubly problematic if you handled other whitespace characters (tab, feed, or new line).
> 
> IMO a better way to handle this would be to return a specialized error if the phrase contains extra spaces. The `Mnemonic::from_phrase` method could then handle that error and try to sanitize the string before retrying.

Thanks for taking time to review.  Can you help me understand this better?  I don't see hashing of the phrase itself, only the bits resulting from the individual words parsed from the phrase.

**Comment by maciejhirsz** [comment]
@rob-solana that's [a bug that's been fixed long ago but hasn't been merged](https://github.com/infincia/bip39-rs/pull/18/files#diff-e50c2050736ce9a0877481845b796a56).

**Comment by rob-solana** [comment]
@maciejhirsz perhaps this PR should be against your fork?

**Comment by maciejhirsz** [comment]
@rob-solana Sure, if you want, I'm happy to include it as long as it doesn't break the seed generation :).

**Pull request closed without merging**
